series: bionic
machines:
  "0":
    series: bionic
    constraints: tags=kafka
  "1":
    series: bionic
    constraints: tags=zookeeper

applications:
  zookeeper:
    charm: cs:~narindergupta/zookeeper
    num_units: 1
    to:
    - 1
  kafka:
    charm: cs:~narindergupta/kafka
    num_units: 1
    options:
      subject_alt_names: testbroker.local
      default_partitions: 1
      default_replication_factor: 1
      log_dir: /var/lib/kafka/
    to:
    - 0
  easyrsa:
    charm: cs:~containers/easyrsa
    num_units: 1
    to:
    - lxd:1
  ntp:
   charm: cs:ntp
   options:
     source: "0.ubuntu.pool.ntp.org 1.ubuntu.pool.ntp.org 2.ubuntu.pool.ntp.org 3.ubuntu.pool.ntp.org"
relations:

- - kafka:zookeeper
  - zookeeper:zookeeper
- - easyrsa:client
  - kafka:certificates
# ntp
- - ntp:juju-info
  - zookeeper:juju-info
- - ntp:juju-info
  - kafka:juju-info
- - ntp:juju-info
  - easyrsa:juju-info

